services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile/frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
