services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile/frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - .env.${ENV:-development}  # 共通・デフォルトの値はここから読み込む
    environment:
      VITE_API_BASE_URL : ${VITE_API_BASE_URL}

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    env_file:
      - .env.${ENV:-development}  # 共通・デフォルトの値はここから読み込む  # rootの.envを参照
    environment:
      OPENAI_API_KEY : ${OPENAI_API_KEY}
      GOOGLE_APPLICATION_CREDENTIALS : ${GOOGLE_APPLICATION_CREDENTIALS}
      GOOGLE_CLOUD_PROJECT : ${GOOGLE_CLOUD_PROJECT}
      GOOGLE_CLOUD_SPEECH_REGION : ${GOOGLE_CLOUD_SPEECH_REGION}
