services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile/nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/www:/var/www/certbot  # certbot用webroot
    depends_on:
      - frontend
      - backend
    env_file:
      - .env.${ENV:-development}  # 共通・デフォルトの値はここから読み込む
    environment:
      SERVER_NAME: ${SERVER_NAME}
    restart: unless-stopped
  
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile/frontend.Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    env_file:
      - .env.${ENV:-development}  # 共通・デフォルトの値はここから読み込む
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile/backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    env_file:
      - .env.${ENV:-development}  # 共通・デフォルトの値はここから読み込む  # rootの.envを参照
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      GOOGLE_CLOUD_SPEECH_REGION: ${GOOGLE_CLOUD_SPEECH_REGION}

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./nginx/certs:/etc/letsencrypt/live
  #     - ./nginx/www:/var/www/certbot
  #   environment:
  #     - CERTBOT_EMAIL=${CERTBOT_EMAIL}
  #     - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${CERTBOT_DOMAIN}
